CREATE TABLE debug_log
(
    log_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    log_time TIMESTAMP
        DEFAULT SYSTIMESTAMP
        NOT NULL,

    module_name VARCHAR2(100)
        NOT NULL,

    line_no NUMBER,

    log_level VARCHAR2(10)
        DEFAULT 'INFO'
        NOT NULL,

    log_message VARCHAR2(4000)
        NOT NULL,

    session_id VARCHAR2(50)
        DEFAULT SYS_CONTEXT('USERENV','SESSIONID')
        NOT NULL,

    CONSTRAINT pk_debug_log
        PRIMARY KEY(log_id)
);